name: Danger Comment

on:
  workflow_run:
    workflows: [Danger]
    types: [completed]

permissions:
  actions: read
  issues: write
  pull-requests: write

jobs:
  comment:
    uses: numbata/danger-pr-comment/.github/workflows/danger-comment.yml@v0.1.0
    secrets: inherit
